In [71]:
import pandas as pd

# postcodes from Berlin
postcodes_de = pd.read_excel(r'ds_mock_datasets/data/original/German-Zip-Codes.xlsx', sheet_name='Berlin')
df = pd.DataFrame(postcodes_de)
df.set_axis(["postcodes_berlin"], axis=1,inplace=True)
df = (df["postcodes_berlin"].str[8:-11])
df.to_csv('ds_mock_datasets/data/postcodes_berlin.csv', index=False)

/var/folders/xs/pmxwbppj14b4v76l4llp17n80000gp/T/ipykernel_62270/3383315515.py:6: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  df.set_axis(["postcodes_berlin"], axis=1,inplace=True)

In [72]:
# !conda install -c conda-forge fake

In [73]:
from faker import Faker, providers
from faker.providers.address.de_DE import Provider as DeDeAddressProvider
from faker.generator import random
from faker.providers import BaseProvider
# from faker.generator import BaseProvider
# import random

### Creating the post code series

In [74]:
postcodes_berlin = pd.read_csv('ds_mock_datasets/data/postcodes_berlin.csv')
postcodes_berlin_series = postcodes_berlin[:][1:].squeeze()

### Creating lists

#### lat lng : choosing random point based on a polygon
reference: 
    A quick trick to create random lat/long coordinates in python (within a defined polygon)
https://medium.com/the-data-journal/a-quick-trick-to-create-random-lat-long-coordinates-in-python-within-a-defined-polygon-e8997f05123a

In [75]:
# Importing Modules
import numpy as np
import random
# Use 'conda install shapely' to import the shapely library.
from shapely.geometry import Polygon, Point

num_records = 10

### Creating the dataset

## dataset for the model
item_id, item_name-item_category_item_dimension (SPLIT LATER), item_lat_lng (SPLIT LATER), item_postcode, 

userwhoposted_id, 

userwhopickedup_id, userwhochangeditemstatus_id, userwhochangeditemstatus_lat_lng (SPLIT LATER), 

> HOW TO BE SURE THAT WHO CHANGED THE STATUS WAS WHO PICKED UP? ASK TO UX TO ADD A QUESTION TO THE USER THAT CHANGED THE STATUS: 'Where you who picked it up?' 

searched_item_name_item_category (SPLIT LATER), searched_postcode,

datetime_posted (SPLIT LATER), datetime_statuschanged(SPLIT LATER)

### Challenging: a condition

datetime_posted < datetime_statuschanged

In [76]:
# Note: # multi_locale_generator = Faker(['it_IT', 'en_US', 'de-DE', 'pt_BR', 'es-ES', 'fr-FR', 'ru-RU', 'tr-TR'])


# Instantiate Faker with multiple locales
german_locale_generator = Faker(['de_DE'])
fake = Faker()
Faker.seed(0)

In [77]:
#  First code, I improved it 

# user_mock_df = pd.DataFrame({'user_name': [german_locale_generator.name() for i in range(num_records)],
#                              'user_email': [german_locale_generator.email() for i in range(num_records)],
#                              'user_address': [german_locale_generator.address() for i in range(num_records)],
#                              'user_type': [random.choices(user_type, k=1) for i in range(num_records)],
#                              'user_lat_lng': [polygon_random_points(poly,1) for i in range(num_records)]
#                               })

# item_mock_df = pd.DataFrame({'item_name-item_category-item_dimension':[random.choices(category_item_dimension, k=1) for i in range(num_records)],
#                             'item_postcode': [random.choices(postcodes_berlin_series, k=1) for i in range(num_records)],
#                             'item_status': [random.choices(item_status, k=1) for i in range(num_records)],
#                             'item_lat_lng': [polygon_random_points(poly,1) for i in range(num_records)],
#                             'item_datetime_posted': [german_locale_generator.date_time_this_year() for i in range(num_records)],
# #                             'item_datetime_statuschanged': 
# #                              'userwhochangeditemstatus_id': 
                             
#                              })

In [78]:
# Define the desired polygon : points choosen in Google maps

poly = Polygon([(52.645883, 13.395869), 
                (52.526568, 13.645808),
                (52.381789, 13.405482),
                (52.484773, 13.136317)])


min_x = 52.381789
max_x = 52.645883
min_y = 13.136317
max_y = 13.645808

# Defining the randomization generator
def polygon_random_points (poly, num_records):
    min_x, min_y, max_x, max_y = poly.bounds
    points = []
    while len(points) < num_records:
        random_point = Point([random.uniform(min_x, max_x), random.uniform(min_y, max_y)])
        if (random_point.within(poly)):
            points.append(random_point)
    return points
    # Choose the number of points desired. T\ 
points = polygon_random_points(poly,num_records)
# Testing the results.
for p in points:
    print(p.x,",",p.y)

52.45172334175628 , 13.272015648118826
52.434300090234665 , 13.286205490542581
52.45953057936675 , 13.449919147684408
52.42492157601415 , 13.308208805965503
52.502334558578966 , 13.582321088886575
52.520184095450624 , 13.468280298774722
52.41487217606013 , 13.414187230853686
52.6295118698936 , 13.383393517675154
52.535946883392896 , 13.58482763858354
52.510190905733744 , 13.29885025401638

In [79]:
# define a function to create user data

user_type = ['giver', 'looker', 'who_pickedup']

def create_user_data(num_records): 
  
    # dictionary 
    user ={} 
    for i in range(0, num_records): 
        user[i] = {} 
        user[i]['name'] = fake.name()
        user[i]['email'] = fake.email()
        user[i]['address'] = german_locale_generator.address()  # these addresses are from germany, find a list of address for berlin
        user[i]['user_type'] = fake.random_element(user_type)
        user[i]['user_lat_lng'] = polygon_random_points(poly,1)
        user[i]['user_postcode'] = np.random.choice(postcodes_berlin_series)

    return user

In [80]:
user_mock_df = pd.DataFrame(create_user_data(1000)).transpose()
user_mock_df.head(5)

,name,email,address,user_type,user_lat_lng,user_postcode
0,Norma Fisher,tammy76@example.com,Alwina-Etzold-Ring 19\n89241 Sömmerda,looker,[POINT (52.53660058612233 13.53392510776923)],12167
1,Brian Hamilton,tammywoods@example.net,Domenico-Ullrich-Straße 975\n51393 Diepholz,who_pickedup,[POINT (52.55974189824938 13.46084703947001)],13051
2,Bobby Flores,jrodriguez@example.com,Walburga-Schleich-Weg 7\n96593 Emmendingen,giver,[POINT (52.54617971099868 13.522144069175)],10317
3,Amanda Zavala,thomas12@example.org,Tröststr. 8\n39694 Neustrelitz,who_pickedup,[POINT (52.48450860061548 13.26150470636124)],12169
4,Melody Haas,christopher91@example.com,Alexej-Wähner-Ring 352\n60123 Riesa,who_pickedup,[POINT (52.48577160588064 13.40583244486403)],10409

In [81]:
# add user_ids 
user_mock_df['user_id'] = user_mock_df.index + 1
user_id_series = user_mock_df['user_id']

In [82]:
item_status = ['avaliable', 'not_available']
category_item_dimension = ['furniture-sofa-136x224x80','furniture-sofa-177x72x86','furniture-sofa-232x97x98'
                             'furniture-armchair-92x84x104',
                             'furniture-chair',
                             'furniture-table',
                             'furniture-bed',
                             'furniture-bookcase',
                             'furniture-bedside_table',
                             'furniture-cabinet',
                             'furniture-rollcontainers',
                             'furniture-shoe_rack',
                             'furniture-mirror',
                             'furniture-cot',
                             'appliance-washing_machine',
                             'appliance-dish_washer',
                             'appliance-drying_rack',
                             'appliance-refrigerator',
                             'appliance-blender',
                             'appliance-extractor_hood',
                             'appliance-clothes_iron',
                             'appliance-vacuum_cleaner',
                             'appliance-sandwich_maker',
                             'appliance-kettle',
                             'appliance-air_conditioner',
                             'appliance-heater',
                             'appliance-pan',
                             'appliance-popcorn_maker',
                             'appliance-coffee_machine',
                             'appliance-stove',
                             'lighting-lighting',
                             'lighting-chandelier',
                             'lighting-lightbulb',
                             'musical_equipment-guitar',
                             'musical_equipment-sound_amplifier',
                             'musical_equipment-contrabass',
                             'musical_equipment-battery',
                             'musical_equipment-piano',
                             'tech-desktop',
                             'tech-laptop',
                             'tech-phone',
                             'tech-keyboard',
                             'clothes-woman_jacket',
                             'clothes-man_jacket',
                             'clothes-child_jacket',
                             'clothes-woman_clothes',
                             'clothes-man_clothes',
                             'clothes-child_clothes',
                             'shoes-woman_shoes',
                             'shoes-manshoes',
                             'shoes-child_shoes',
                             'miscelaneaous-ironing_board',
                             'miscelaneaous-baby_carriage',
                             'miscelaneaous-picture_frame',
                             'miscelaneaous-bicycle',
                             'miscelaneaous-plant',
                             'miscelaneaous-carpet',
                             'miscelaneaous-roller_skates',
                             'miscelaneaous-ski_skates']

In [99]:
# define a function to create item data

def create_item_data(num_records): 
  
    # dictionary 
    item ={} 
    for i in range(0, num_records): 
        item[i] = {}
        item[i]['item_name-item_category-item_dimension'] = np.random.choice(category_item_dimension)
        item[i]['item_postcode'] = np.random.choice(postcodes_berlin_series)
        item[i]['item_status'] = np.random.choice(item_status)
        item[i]['user_lat_lng'] = polygon_random_points(poly,1)
        item[i]['userwhochangeditemstatus_id'] = np.random.choice(user_id_series)
        datetime_iteration1 = fake.date_between_dates('-7d','now')
        datetime_iteration2 = fake.date_between_dates('-7d','now')
        if datetime_iteration1 <= datetime_iteration2:
            item[i]['item_datetime_posted'] = datetime_iteration1
            item[i]['item_datetimechangeditemstatus'] = datetime_iteration2
        else:
            item[i]['item_datetime_posted'] = datetime_iteration2
            item[i]['item_datetimechangeditemstatus'] = datetime_iteration1  
 # This date shold be later than the post
        

    return item

In [100]:
item_mock_df = pd.DataFrame(create_item_data(1000)).transpose()
item_mock_df.head(5)

,item_name-item_category-item_dimension,item_postcode,item_status,user_lat_lng,userwhochangeditemstatus_id,item_datetime_posted,item_datetimechangeditemstatus
0,appliance-stove,12053,not_available,[POINT (52.43559651341142 13.36408980994966)],350,2023-02-21,2023-02-23
1,appliance-extractor_hood,14129,avaliable,[POINT (52.51908502546481 13.55949937832306)],205,2023-02-18,2023-02-19
2,shoes-manshoes,13129,not_available,[POINT (52.59446201861163 13.40023676580963)],566,2023-02-21,2023-02-23
3,furniture-bedside_table,10999,avaliable,[POINT (52.5795680468667 13.33674139764294)],880,2023-02-19,2023-02-21
4,furniture-bedside_table,12209,avaliable,[POINT (52.48506703573302 13.48444070443428)],554,2023-02-23,2023-02-23

In [85]:
# item_mock_df = pd.DataFrame({'item_name-item_category-item_dimension':[random.choices(category_item_dimension, k=1) for i in range(num_records)],
#                             'item_postcode': [random.choices(postcodes_berlin_series, k=1) for i in range(num_records)],
#                             'item_status': [random.choices(item_status, k=1) for i in range(num_records)],
#                             'item_lat_lng': [polygon_random_points(poly,1) for i in range(num_records)],
#                             'item_datetime_posted': [german_locale_generator.date_time_this_year() for i in range(num_records)],
# #                             'item_datetime_statuschanged': 
# #                              'userwhochangeditemstatus_id': 
#                              })

In [86]:
item_mock_df['item_id'] = item_mock_df.index +1  # add item_id
item_id_series = item_mock_df['item_id']  # storage in a variable to use later

In [96]:
# define a function to create model data

def create_model_data(num_records): 
  
    # dictionary 
    model ={} 
    for i in range(0, num_records): 
        model[i] = {} 
        model[i]['item_id'] = np.random.choice(item_id_series)
        model[i]['item_name-item_category-item_dimension'] = np.random.choice(category_item_dimension)
        model[i]['item_lat_lng'] = polygon_random_points(poly,1)
        model[i]['item_postcode'] = np.random.choice(postcodes_berlin_series)
        model[i]['item_status'] = np.random.choice(item_status)
        model[i]['userwhoposted_id'] = np.random.choice(user_id_series)
        model[i]['userwhopickedup_id'] = np.random.choice(user_id_series)
        model[i]['userwhochangeditemstatus_id'] = np.random.choice(user_id_series)
        model[i]['userwhochangeditemstatus_lat_lng'] = polygon_random_points(poly,1)
        model[i]['searched_item_name-searched_item_category-searched_item_dimension'] = np.random.choice(category_item_dimension)
        model[i]['searched_postcode'] = np.random.choice(postcodes_berlin_series)
        datetime_iteration1 = fake.date_between_dates('-7d','now')
        datetime_iteration2 = fake.date_between_dates('-7d','now')
        if datetime_iteration1 <= datetime_iteration2:
            model[i]['item_datetime_posted'] = datetime_iteration1
            model[i]['item_datetimechangeditemstatus'] = datetime_iteration2
        else:
            model[i]['item_datetime_posted'] = datetime_iteration2
            model[i]['item_datetimechangeditemstatus'] = datetime_iteration1  
       
    return model

In [97]:
model_mock_df = pd.DataFrame(create_model_data(1000)).transpose()
model_mock_df.head(5)

,item_id,item_name-item_category-item_dimension,item_lat_lng,item_postcode,item_status,userwhoposted_id,userwhopickedup_id,userwhochangeditemstatus_id,userwhochangeditemstatus_lat_lng,searched_item_name-searched_item_category-searched_item_dimension,searched_postcode,item_datetime_posted,item_datetimechangeditemstatus
0,427,miscelaneaous-baby_carriage,[POINT (52.43601127479408 13.27205606872747)],14052,avaliable,730,949,476,[POINT (52.43264390961758 13.32430520866262)],tech-keyboard,12167,2023-02-12 11:14:26,2023-02-16 09:33:24
1,937,clothes-child_clothes,[POINT (52.50104364959809 13.27551949202928)],14193,avaliable,940,49,819,[POINT (52.50828507500001 13.20395221958889)],tech-desktop,10709,2023-01-08 04:12:19,2023-02-11 07:33:26
2,609,clothes-child_clothes,[POINT (52.46070720596612 13.28146022331773)],12101,avaliable,634,268,135,[POINT (52.43596515782288 13.35758508030358)],appliance-stove,14163,2023-01-05 06:31:54,2023-02-18 22:47:54
3,975,appliance-coffee_machine,[POINT (52.60118619625221 13.36436894689052)],14163,not_available,921,456,105,[POINT (52.5491942216098 13.4753962287973)],lighting-lighting,10243,2023-02-06 05:14:17,2023-02-19 01:23:35
4,817,appliance-refrigerator,[POINT (52.55112613697876 13.43826158752375)],10367,not_available,591,137,18,[POINT (52.56528196242276 13.46384533266778)],musical_equipment-guitar,12203,2023-01-31 05:58:45,2023-02-13 19:42:28

In [89]:
# item_id_series = item_mock_df['item_id']
# user_id_series = user_mock_df['user_id']

# for_model_mock_df = pd.DataFrame({'item_id': [random.choices(item_id_series, k=1) for i in range(num_records)],
#                                   'item_name-item_category-item_dimension': [random.choices(category_item_dimension, k=1) for i in range(num_records)],  
#                                   'item_lat_lng': [polygon_random_points(poly,1) for i in range(num_records)], 
#                                   'item_postcode': [random.choices(postcodes_berlin_series, k=1) for i in range(num_records)], 
#                                   'item_status':
#                                   'userwhoposted_id': [random.choices(user_id_series, k=1) for i in range(num_records)],
#                                   'userwhopickedup_id': [random.choices(user_id_series, k=1) for i in range(num_records)], 
#                                   'userwhochangeditemstatus_id': [random.choices(user_id_series, k=1) for i in range(num_records)], 
#                                   'userwhochangeditemstatus_lat_lng': [polygon_random_points(poly,1) for i in range(num_records)],
#                                   'searched_item_name-searched_item_category-searched_item_dimension': [random.choices(category_item_dimension, k=1) for i in range(num_records)], 
#                                   'searched_postcode': [random.choices(postcodes_berlin_series, k=1) for i in range(num_records)],
#                                   'item_datetime_posted': [german_locale_generator.date_time_this_year() for i in range(num_records)], 
# #                                   'item_datetime_statuschanged': [german_locale_generator.date_time_this_year() for i in range(num_records) if german_locale_generator.date_time_this_year() > item_datetime_posted]
#                                   })

### COULD HAVE:  Create a data frame with item_id and item_picture

In [90]:

# item_picture_mock_df = pd.DataFrame({item_mock_df['item_id'].
#                            'item_datetime_picture':

### TODOs:
- ADD dimensions in 'item_name-item_category-item_dimension'
- ADD 'item_datetime_statuschanged'(LATEST THE 'item_datetime_posted'  [WIP]
- FIX DTYPES
- ADD WEIGHT FOR VALUES
- ADD BLANKS?
- ADD 'item_picture'
- FIND AND API FOR ADDRESSES IN BERLIN
- COULD HAVE: DOWNLOAD PICTURES USING API: https://unsplash.com/developers

QUESTIONS:
- HOW LONG DO THE ITEMS GET IN THE APP? (IF NOBODY CHANGE ITS STATUS?) WHAT ABOUT 7 DAYS?

In [91]:
# strings_users = ['uaser_name', 'user_type']
# strings_items = ['item_name', 'postcodes', 'status']

References:

- [Generate custom datasets using Python Faker](https://blogs.sap.com/2021/05/26/generate-custom-datasets-using-python-faker/)